### ISSUE TITLE
TYPO3 Version 8

### ISSUE THREAD

**Issue by ghost** [alexanderschnitzler/fluid-styled-responsive-images#24]
Do you add support for TYPO3 8 ?

Greetings.

**Comment by cedricziel** [comment]
Hi @devtroll (nice nick, btw ^^),

yeah.. it's been rumoured that there should eventually be a consstent responsive images support in TYPO3 itself. I would much rather have the core manage image generation without manual interception from the outside.

I would really love pull requests on that matter - otherwise yes, i'm pretty sure we'll have v8 support with 8 LTS.

**Comment by ghost** [comment]
Okay thanks. I wait for the update from your plugin.

**Comment by cedricziel** [comment]
Hi @devtroll ,

I've marked the extension as compatible.

Cheers,
Cedric
